#[Backend]
backend = "auto"         # Backend to use: "auto", "hyprland", "hyprsunset" or "wayland"
transition_mode = "geo"  # Select: "geo", "finish_by", "start_at", "center", "static"

#[Smoothing]
smoothing = true
startup_duration = 0.5
shutdown_duration = 0.5
adaptive_interval = 1

#[Time-based config]
night_temp = 3300
day_temp = 6500
night_gamma = 90
day_gamma = 100
update_interval = 60

#[Static config]
static_temp = 6500
static_gamma = 100

#[Manual transitions]
sunset = "19:00:00"
sunrise = "06:00:00"
transition_duration = 45

#[Geolocation]
latitude = 53.550000
longitude = 10.000000
