#! /usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a VLC state=floating
bspc rule -a Firefox desktop='^1'
firefox &

setxkbmap de neo -option

xrandr --output eDP-1 --scale 0.7x0.7

# To work around "grey" boxes in Java apps
wmname LG3D &

redshift-gtk &
"$HOME"/.config/polybar/launch.sh
compton &
