#! /usr/bin/env bash

pgrep -x sxhkd > /dev/null || sxhkd -m 1 &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          12

bspc config focused_border_color \#FF4500
bspc config active_border_color \#DAF7A6

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
 bspc config single_monocle       true

bspc rule -a VLC state=floating
bspc rule -a Firefox desktop='^1'
firefox &

setxkbmap de neo -option

wmname LG3D
export _JAVA_AWT_WM_NONREPARENTTING=1

picom &
"$HOME"/.config/polybar/launch_multimonitor.sh
redshift-gtk &
dunst &
libinput-gestures &
