[manager]

prepend_keymap = [
  { on = "D",         run = "remove",                      desc = "Trash selected files" },
  { on = "d",         run = "remove --permanently",        desc = "Permanently delete selected files" },
  { on = "l",         run = "plugin --sync smart-enter",   desc = "Enter the child directory, or open the file" },
  { on = "<Enter>",   run = "plugin --sync smart-enter",   desc = "Enter the child directory, or open the file" },
]

