[user]
name = "Lars Francke"
email = "jujutsu@lars-francke.de"

[ui]
default-command = "log"

[signing]
behavior = "own"
backend = "ssh"
key = "/home/lars/.ssh/id_ed25519.pub"

[snapshot]
auto-track = "none()"

[revset-aliases]
interesting = '''
  ancestors(reachable(
    mine() | @,
    mutable(),
  ), 2)
  | trunk() | @
'''

[revsets]
log = "interesting"
